apiVersion: v1
kind: Service
metadata:
  name: {{ include "ihpw.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ihpw.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ihpw.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
    {{- end }}
